In [2]:
import numpy as np

In [8]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [9]:
#変形（reshape)
#↓の場合は2行、３列の２次元配列に変換する
c2 = c1.reshape((2 , 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])