In [1]:
import numpy as np
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

In [10]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [12]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [13]:
c2 = c1.reshape((2 ,3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [15]:
c4 = c2.flatten() #コピーを返す
c4

array([0, 1, 2, 3, 4, 5])

In [17]:
a.dtype

dtype('int64')

In [18]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [19]:
d.dtype

dtype('int16')

In [10]:
import numpy as np
a = np.array([1, 2, 3])

In [11]:
a

array([1, 2, 3])

In [12]:
a[0]

np.int64(1)

In [13]:
a[1:]

array([2, 3])

In [14]:
a[-1]

np.int64(3)

In [15]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b[0]

array([1, 2, 3])

In [18]:
b[1, 0]

np.int64(4)

In [19]:
b[:, 2]

array([3, 6])

In [20]:
b[1, :]

array([4, 5, 6])

In [21]:
b[0, 1:]

array([2, 3])

In [2]:
import numpy as np
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
a[2] = 4
a

array([1, 2, 4])

In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [8]:
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [9]:
a1 = a
a1

array([1, 2, 4])

In [10]:
a1[1] = 5
a1

array([1, 5, 4])

In [11]:
a

array([1, 5, 4])

In [12]:
a2 = a.copy()
a2

array([1, 5, 4])

In [13]:
a2[0] = 6
a2

array([6, 5, 4])

In [14]:
a

array([1, 5, 4])

In [17]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [18]:
c2 = c1.reshape((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7

In [20]:
c3

array([6, 1, 2, 3, 4, 5])

In [21]:
c4

array([0, 7, 2, 3, 4, 5])

In [22]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [27]:
rng = np.random.default_rng()
f = rng.random((3, 2))
f

array([[0.89486578, 0.76218585],
       [0.10059054, 0.47180197],
       [0.54004667, 0.95459599]])

In [28]:
rng = np.random.default_rng()
f = rng.random((4, 3))
f

array([[0.48785441, 0.91437509, 0.57407477],
       [0.581774  , 0.24584188, 0.85324122],
       [0.01294637, 0.90512999, 0.76808916],
       [0.0137807 , 0.13656205, 0.4494501 ]])

In [3]:
import numpy as np

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones(2)

array([1., 1.])

In [7]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [10]:
np.full((2, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [11]:
np.nan

nan

In [12]:
np.array([1, 2, np.nan])

array([ 1.,  2., nan])

In [13]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.linspace(0, np.pi, 21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [15]:
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

In [16]:
a = np.array([1, 2, 3])
a1 = a

In [17]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [19]:
np.concatenate([a, a1])

array([1, 2, 3, 1, 2, 3])

In [24]:
b1 = np.array([[10], [20]])
b1

array([[10],
       [20]])

In [27]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.concatenate([b, b1], axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [30]:
np.hstack([b, b1])

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [31]:
b2 = np.array([30, 60, 45])
b2

array([30, 60, 45])

In [32]:
b3 = np.vstack([b, b2])
b3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [30, 60, 45]])

In [33]:
b3 = np.vstack([b, b2])
b3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [30, 60, 45]])

In [3]:
import numpy as np

In [5]:
b1 = np.array([[10], [20]])
b1

array([[10],
       [20]])

In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b2 = np.array([30, 60, 45])
b2

array([30, 60, 45])

In [8]:
b3 = np.vstack([b, b2])
b3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [30, 60, 45]])

In [9]:
first, second = np.hsplit(b3, [2])

In [10]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [11]:
second

array([[ 3],
       [ 6],
       [45]])

In [12]:
first1, second1 = np.vsplit(b3, [2])

In [13]:
first1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
second1

array([[30, 60, 45]])

In [15]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
a = np.array([1, 2, 3])

In [18]:
a[np.newaxis, :]

array([[1, 2, 3]])

In [19]:
a[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [22]:
m = np.arange(0, 4)
m

array([0, 1, 2, 3])

In [23]:
n = np.arange(4 ,7)
n

array([4, 5, 6])

In [24]:
xx, yy = np.meshgrid(m, n)
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [25]:
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [26]:
import numpy as np

a = np.arange(3)
b = np.arange(-3, 3).reshape((2, 3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 1, 10)
print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)
print("e:", e)

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [27]:
print("a:",a.shape)
print("b:",b.shape)
print("c:",c.shape)
print("d:",d.shape)
print("e:",e.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)


In [28]:
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [29]:
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [30]:
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [31]:
np.log(a)

C:\Users\wc-to\AppData\Local\Temp\ipykernel_20360\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718])

In [32]:
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [34]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [35]:
a

array([0, 1, 2])

In [36]:
a + 10

array([10, 11, 12])

In [37]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [38]:
a + b

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [39]:
a1 = a[:, np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [40]:
a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [41]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
c - np.mean(c)

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [43]:
b * 2

array([[-6, -4, -2],
       [ 0,  2,  4]])

In [44]:
b ** 3

array([[-27,  -8,  -1],
       [  0,   1,   8]])

In [45]:
b - a

array([[-3, -3, -3],
       [ 0,  0,  0]])

In [46]:
a * b

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [47]:
a / c

array([[0.        , 0.5       , 0.66666667],
       [0.        , 0.2       , 0.33333333]])

In [48]:
c / a

C:\Users\wc-to\AppData\Local\Temp\ipykernel_20360\357454608.py:1: RuntimeWarning: divide by zero encountered in divide
  c / a


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

In [50]:
c / (a+1e-6)

array([[1.00000000e+06, 1.99999800e+00, 1.49999925e+00],
       [4.00000000e+06, 4.99999500e+00, 2.99999850e+00]])

In [51]:
np.dot(b, a)

array([-4,  5])

In [52]:
b @ a

array([-4,  5])

In [53]:
b @ d

array([[ -8, -14],
       [ 10,  13]])

In [54]:
b @ d

array([[ -8, -14],
       [ 10,  13]])

In [55]:
d @ b

array([[  0,   1,   2],
       [ -6,  -1,   4],
       [-12,  -3,   6]])

In [56]:
a > 1

array([False, False,  True])

In [57]:
b > 0

array([[False, False, False],
       [False,  True,  True]])

In [58]:
np.count_nonzero(b > 0)

np.int64(2)

In [59]:
np.sum(b > 0)

np.int64(2)

In [60]:
np.any(b > 0)

np.True_

In [61]:
np.all(b > 0)

np.False_

In [62]:
b[b > 0]

array([1, 2])

In [63]:
b == c

array([[False, False, False],
       [False, False, False]])

In [64]:
a == b

array([[False, False, False],
       [ True,  True,  True]])

In [65]:
(b == c) | (a == b)

array([[False, False, False],
       [ True,  True,  True]])

In [67]:
b[(b == c) | (a == b)]

array([0, 1, 2])

In [ ]:
np.allc