In [1]:
import numpy as np
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

In [10]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [12]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [13]:
c2 = c1.reshape((2 ,3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [15]:
c4 = c2.flatten() #コピーを返す
c4

array([0, 1, 2, 3, 4, 5])

In [17]:
a.dtype

dtype('int64')

In [18]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [19]:
d.dtype

dtype('int16')

In [10]:
import numpy as np
a = np.array([1, 2, 3])

In [11]:
a

array([1, 2, 3])

In [12]:
a[0]

np.int64(1)

In [13]:
a[1:]

array([2, 3])

In [14]:
a[-1]

np.int64(3)

In [15]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b[0]

array([1, 2, 3])

In [18]:
b[1, 0]

np.int64(4)

In [19]:
b[:, 2]

array([3, 6])

In [20]:
b[1, :]

array([4, 5, 6])

In [21]:
b[0, 1:]

array([2, 3])