In [1]:
import numpy as np

In [8]:
#1次元配列
a = np.array([1, 2, 3])

In [9]:
a

array([1, 2, 3])

In [3]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [4]:
#変形（reshape)
#↓の場合は2行、３列の２次元配列に変換する
c2 = c1.reshape((2 , 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
#変換（ravel)
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [6]:
#copyを返す
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [10]:
a.dtype

dtype('int64')