In [1]:
import numpy as np

In [6]:
#1次元配列
a = np.array([1, 2, 3])

In [7]:
a

array([1, 2, 3])

In [14]:
b = np.array([[1, 2, 3],[4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [4]:
#変形（reshape)
#↓の場合は2行、３列の２次元配列に変換する
c2 = c1.reshape((2 , 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
#変換（ravel)
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [6]:
#copyを返す
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [10]:
a.dtype

dtype('int64')

In [2]:
d = np.array([1, 2], dtype=np.int16)#np.int16の型宣言
d

array([1, 2], dtype=int16)

In [3]:
d.dtype

dtype('int16')

In [4]:
#astypeメソッドで型変換する
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [8]:
a

array([1, 2, 3])

In [9]:
a[0]#先頭データの取得

np.int64(1)

In [10]:
a[1:]#スライス １番目～

array([2, 3])

In [11]:
a[-1]#末尾から数える

np.int64(3)

In [15]:
b

array([[1, 2, 3],
       [4, 5, 6]])