In [1]:
import numpy as np
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

In [10]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [12]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [13]:
c2 = c1.reshape((2 ,3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [15]:
c4 = c2.flatten() #コピーを返す
c4

array([0, 1, 2, 3, 4, 5])

In [17]:
a.dtype

dtype('int64')

In [18]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [19]:
d.dtype

dtype('int16')

In [10]:
import numpy as np
a = np.array([1, 2, 3])

In [11]:
a

array([1, 2, 3])

In [12]:
a[0]

np.int64(1)

In [13]:
a[1:]

array([2, 3])

In [14]:
a[-1]

np.int64(3)

In [15]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b[0]

array([1, 2, 3])

In [18]:
b[1, 0]

np.int64(4)

In [19]:
b[:, 2]

array([3, 6])

In [20]:
b[1, :]

array([4, 5, 6])

In [21]:
b[0, 1:]

array([2, 3])

In [2]:
import numpy as np
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
a[2] = 4
a

array([1, 2, 4])

In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b[1, 2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [8]:
b[:, 2] = 8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [9]:
a1 = a
a1

array([1, 2, 4])

In [10]:
a1[1] = 5
a1

array([1, 5, 4])

In [11]:
a

array([1, 5, 4])

In [12]:
a2 = a.copy()
a2

array([1, 5, 4])

In [13]:
a2[0] = 6
a2

array([6, 5, 4])

In [14]:
a

array([1, 5, 4])

In [17]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [18]:
c2 = c1.reshape((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7

In [20]:
c3

array([6, 1, 2, 3, 4, 5])

In [21]:
c4

array([0, 7, 2, 3, 4, 5])

In [22]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [27]:
rng = np.random.default_rng()
f = rng.random((3, 2))
f

array([[0.89486578, 0.76218585],
       [0.10059054, 0.47180197],
       [0.54004667, 0.95459599]])

In [28]:
rng = np.random.default_rng()
f = rng.random((4, 3))
f

array([[0.48785441, 0.91437509, 0.57407477],
       [0.581774  , 0.24584188, 0.85324122],
       [0.01294637, 0.90512999, 0.76808916],
       [0.0137807 , 0.13656205, 0.4494501 ]])