In [3]:
import numpy as np

In [3]:
a = np.array([3, 7, 2, 9, 4, 8])

In [7]:
np.average(a)

np.float64(5.5)

In [5]:
np.max(a)

np.int64(9)

In [6]:
np.min(a)

np.int64(2)

In [7]:
np.std(a)

np.float64(2.6299556396765835)

In [11]:
np.where(a>5)

(array([1, 3, 5]),)

In [5]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
b.shape

(3, 3)

In [8]:
b[:,2]

array([3, 6, 9])

In [10]:
b[1,:]

array([4, 5, 6])

In [11]:
np.sum(b)

np.int64(45)